//%attributes = {}
Begin SQL
	
	ALTER TABLE BOUTIQUE ADD ID_Evenement INT32;
	
	ALTER TABLE BOUTIQUE
	ADD CONSTRAINT fk_evenementBoutique FOREIGN KEY
	(ID_Evenement) REFERENCES EVENEMENT (ID)
	ON DELETE RESTRICT ON UPDATE RESTRICT;
	
End SQL

ALERT:C41("Done")